function: taper
info:
  length: 10.0
  width1: 0.5
  width2: 0.5
module: gdsfactory.components.taper
name: taper
settings:
  cross_section: xs_sc
  length: 10.0
  port_names:
  - o1
  - o2
  port_types:
  - optical
  - optical
  width1: 0.5
  with_two_ports: true
