function: grating_coupler_rectangular
info:
  polarization: te
  wavelength: 1.55
module: gdsfactory.components.grating_coupler_rectangular
name: grating_coupler_rectangular
settings:
  cross_section: xs_sc
  fill_factor: 0.5
  length_taper: 150.0
  n_periods: 20
  period: 0.75
  polarization: te
  slab_offset: 1.0
  slab_xmin: -1.0
  taper:
    function: taper
  wavelength: 1.55
  width_grating: 11.0
