function: straight_heater_metal_simple
info:
  resistance: 0
module: gdsfactory.components.straight_heater_metal
name: straight_heater_metal_simple
settings:
  cross_section_heater: xs_heater_metal
  cross_section_waveguide_heater: xs_sc_heater_metal
  heater_taper_length: 5.0
  length: 320.0
  straight:
    function: straight
  via_stack: via_stack_heater_mtop
