function: array_with_via
info: {}
module: gdsfactory.components.array_with_via
name: array_with_via
settings:
  columns: 3
  component:
    function: pad
  cross_section:
    function: cross_section
    module: gdsfactory.cross_section
    settings:
      layer: M2
      port_names:
      - e1
      - e2
      port_types:
      - electrical
      - electrical
      radius: null
      width: 10.0
  port_orientation: 180
  spacing: 150.0
  straight_length: 60.0
  via_spacing: 10.0
  via_stack:
    function: via_stack
  via_stack_dy: 0
