function: straight
info:
  length: 10.0
  route_info_length: 10.0
  route_info_type: xs_8bf2c479
  route_info_weight: 10.0
  route_info_xs_8bf2c479_length: 10.0
  width: 0.5
module: gdsfactory.components.straight
name: straight_fee9dcda
settings:
  cross_section:
    function: cross_section
    module: gdsfactory.cross_section
    settings:
      radius: 20
      radius_min: 20
      sections:
      - hidden: false
        layer: SLAB90
        name: slab
        offset: 0
        port_names:
        - null
        - null
        port_types:
        - optical
        - optical
        simplify: 0.05
        width: 6.0
  length: 10.0
  npoints: 2
