function: add_fiducials
info:
  xsize: 100.0
  ysize: 100.0
module: gdsfactory.components.add_fiducials
name: add_fiducials
settings:
  component:
    function: pad_array
  gap: 50
  left: cross
  offset:
  - 0
  - 0
  right: cross
