function: greek_cross
info: {}
module: gdsfactory.components.greek_cross
name: greek_cross
settings:
  layers:
  - WG
  - N
  length: 30
  via_stack:
    function: via_stack
    module: gdsfactory.components.via_stack
    settings:
      layers:
      - WG
      - NPP
      - M1
      vias:
      - null
      - null
      - function: via
        module: gdsfactory.components.via
        settings:
          layer: VIAC
  widths:
  - 2.0
  - 3.0
