function: bend_circular
info:
  dy: 0.0
  length: 31.415
  radius: 10.0
  route_info_length: 31.415
  route_info_n_bend_90: 2.0
  route_info_type: xs_sc
  route_info_weight: 31.415
  route_info_xs_sc_length: 31.415
module: gdsfactory.components.bend_circular
name: bend_circular_angle180
settings:
  angle: 180
  cross_section: xs_sc
