function: ring_double
info: {}
module: gdsfactory.components.ring_double
name: ring_double
settings:
  bend:
    function: bend_euler
  coupler_ring:
    function: coupler_ring
  cross_section: xs_sc
  gap: 0.2
  length_x: 0.01
  length_y: 0.01
  radius: 10.0
  straight:
    function: straight
