function: component_lattice
info: {}
module: gdsfactory.components.component_lattice
name: component_lattice
settings:
  grid_per_unit: 1000
  lattice: "\n        C-X\n        CXX\n        CXX\n        C-X\n        "
