function: add_fiber_array_optical_south_electrical_north
info: {}
module: gdsfactory.components.add_fiber_array_optical_south_electrical_north
name: mzi_add_fiber_array_optical_south_electrical_north
settings:
  component:
    function: mzi
    module: gdsfactory.components.mzi
    settings:
      length_x: 200
      straight_x_top: straight_heater_metal
  electrical_port_orientation: 90
  fiber_spacing: 127.0
  grating_coupler:
    function: grating_coupler_elliptical
  pad:
    function: pad
    module: gdsfactory.components.pad
    settings:
      size:
      - 80
      - 80
  pad_gc_spacing: 250.0
  pad_spacing: 100.0
  with_loopback: true
  xs_metal: xs_metal_routing
