function: taper_cross_section
info:
  length: 10
  route_info_length: 10.0
  route_info_type: xs_sc_rc_tip
  route_info_weight: 10.0
  route_info_xs_sc_rc_tip_length: 10.0
  route_info_xs_sc_rc_tip_taper_length: 10
module: gdsfactory.components.taper_cross_section
name: taper_cross_section_npoints101
settings:
  cross_section1:
    function: cross_section
    module: gdsfactory.cross_section
    settings:
      radius: 10
      radius_min: 5
      sections:
      - hidden: false
        layer: SLAB90
        name: slab
        offset: 0
        port_names:
        - null
        - null
        port_types:
        - optical
        - optical
        width: 0.2
  cross_section2: xs_rc
  length: 10
  linear: false
  npoints: 101
  width_type: sine
