function: straight_heater_meander_doped
info: {}
module: gdsfactory.components.straight_heater_meander_doped
name: straight_heater_meander_doped
settings:
  cross_section: xs_sc
  extension_length: 15.0
  heater_width: 1.5
  layers_doping:
  - P
  - PP
  - PPP
  length: 300.0
  radius: 5.0
  spacing: 2.0
  straight_widths:
  - 0.8
  - 0.9
  - 0.8
  taper_length: 10
  via_stack:
    function: via_stack
    module: gdsfactory.components.via_stack
    settings:
      layers:
      - M1
      - M2
      size:
      - 1.5
      - 1.5
      vias:
      - function: via
        module: gdsfactory.components.via
        settings:
          enclosure: 0.1
          layer: VIAC
          size:
          - 0.1
          - 0.1
          spacing:
          - 0.2
          - 0.2
      - function: via
        module: gdsfactory.components.via
        settings:
          enclosure: 0.1
          layer: VIA1
          size:
          - 0.1
          - 0.1
          spacing:
          - 0.2
          - 0.2
