function: bend_straight_bend
info: {}
module: gdsfactory.components.bend_euler
name: bend_straight_bend
settings:
  angle: 90
  cross_section:
    function: cross_section
    module: gdsfactory.cross_section
    settings:
      radius: 10
      radius_min: 5
  direction: ccw
  npoints: 720
  p: 0.5
  straight_length: 10.0
  with_arc_floorplan: true
