function: crossing45
info:
  bezier_length: 42.085
  min_bend_radius: 44.312
module: gdsfactory.components.crossing_waveguide
name: crossing45
settings:
  alpha: 0.08
  cross_section: xs_sc
  cross_section_bends: xs_sc
  crossing:
    function: crossing
  npoints: 101
  port_spacing: 40.0
