function: die_bbox
info:
  area: 3380000.0
module: gdsfactory.components.die_bbox
name: rectangle_die_bbox
settings:
  component:
    function: rectangle
    module: gdsfactory.components.rectangle
    settings:
      size:
      - 1300
      - 2600
  layer: MTOP
  padding: 10.0
  street_width: 100.0
  text_anchor: sw
  text_size: 100.0
