function: via
info:
  enclosure: 1.0
  size:
  - 0.7
  - 0.7
  spacing:
  - 2.0
  - 2.0
  xsize: 0.7
  xspacing: 2.0
  ysize: 0.7
  yspacing: 2.0
module: gdsfactory.components.via
name: via_layerVIA2
settings:
  enclosure: 1.0
  layer: VIA2
  size:
  - 0.7
  - 0.7
  spacing:
  - 2.0
  - 2.0
