function: via_stack_from_rules
info:
  layer: MTOP
  xsize: 1.2
  ysize: 1.2
module: gdsfactory.components.via_stack
name: via_stack_from_rules
settings:
  layers:
  - M1
  - M2
  - MTOP
  size:
  - 1.2
  - 1.2
  via_min_enclosure:
  - 0.15
  - 0.25
  via_min_gap:
  - - 0.1
    - 0.1
  - - 0.1
    - 0.1
  via_min_size:
  - - 0.2
    - 0.2
  - - 0.2
    - 0.2
  vias:
  - function: via
    module: gdsfactory.components.via
    settings:
      enclosure: 2
      layer: VIA1
  - function: via
    module: gdsfactory.components.via
    settings:
      layer: VIA2
