function: grating_coupler_tree
info: {}
module: gdsfactory.components.grating_coupler_tree
name: grating_coupler_tree
settings:
  bend: bend_euler
  fanout_length: 0.0
  grating_coupler:
    function: grating_coupler_elliptical
  n: 4
  straight_spacing: 4.0
  with_loopback: false
