function: mzi_arms
info: {}
module: gdsfactory.components.mzi_arms
name: mzi_arms
settings:
  bend:
    function: bend_euler
  delta_length: 10.0
  delta_yright: 0
  length_x: 0.1
  length_y: 0.8
  splitter:
    function: mmi1x2
  straight:
    function: straight
  with_splitter: true
