function: mzi
info: {}
module: gdsfactory.components.mzi
name: mzi_a42a8e63
settings:
  add_electrical_ports_bot: true
  add_optical_ports_arms: false
  bend:
    function: bend_euler
  cross_section:
    function: cross_section
  delta_length: 10.0
  length_x: 0.1
  length_y: 2.0
  min_length: 0.01
  mirror_bot: false
  nbends: 2
  port_e0_combiner: o3
  port_e0_splitter: o3
  port_e1_combiner: o2
  port_e1_splitter: o2
  splitter:
    function: mmi1x2
    module: gdsfactory.components.mmi1x2
    settings:
      cross_section:
        function: cross_section
      gap_mmi: 0.25
      length_mmi: 5.5
      length_taper: 10.0
      taper:
        function: taper
      width_mmi: 2.5
      width_taper: 1.0
  straight:
    function: straight
  with_splitter: true
