function: spiral_inner_io_fiber_array
info:
  length: 20000.009
  polarization: te
  wavelength: 1.53
module: gdsfactory.components.spiral_inner_io
name: spiral_inner_io_fiber_array
settings:
  N: 6
  add_grating_couplers:
    function: add_grating_couplers_with_loopback_fiber_array
  asymmetric_cross_section: false
  bend180:
    function: bend_euler
    module: gdsfactory.components.bend_euler
    settings:
      angle: 180
  bend90:
    function: bend_euler
  cross_section: xs_sc
  cross_section_loopback: xs_sc
  grating_spacing: 127.0
  length: 20000.0
  straight:
    function: straight
  waveguide_spacing: 3.0
  x_straight_inner_left: 50.0
  x_straight_inner_right: 150.0
  y_straight_inner_bottom: 10.0
  y_straight_inner_top: 50.0
