function: straight_heater_metal_undercut
info:
  resistance: 0
module: gdsfactory.components.straight_heater_metal
name: straight_heater_metal_undercut_68a15837
settings:
  cross_section: xs_sc
  cross_section_heater: xs_heater_metal
  cross_section_heater_undercut: xs_sc_heater_metal_undercut
  cross_section_waveguide_heater: xs_sc_heater_metal
  heater_taper_length: 5.0
  length: 320.0
  length_straight: 0.1
  length_straight_input: 0.1
  length_undercut: 5
  length_undercut_spacing: 0
  port_orientation1: 90
  port_orientation2: 90
  straight:
    function: straight
  via_stack: via_stack_heater_mtop
  with_undercut: false
