function: spiral_inner_io_fiber_single
info:
  length: 9973.393
module: gdsfactory.components.spiral_inner_io
name: spiral_inner_io_fiber_single
settings:
  cross_section: xs_sc
  grating_spacing: 200.0
  x_straight_inner_left: 75.0
  x_straight_inner_right: 40.0
  y_straight_inner_bottom: 0.0
  y_straight_inner_top: 10.0
