function: spiral_racetrack_fixed_length
info:
  length: 999.9991273714644
  straight_length: 65.46151592143306
module: gdsfactory.components.spiral_heater
name: spiral_racetrack_fixed_length
settings:
  bend_factory:
    function: bend_euler
  bend_s_factory:
    function: bend_s
  cross_section: xs_sc
  in_out_port_spacing: 150
  length: 1000
  min_radius: 5.0
  min_spacing: 5.0
  n_straight_sections: 8
  straight_factory:
    function: straight
  with_inner_ports: false
