function: grating_coupler_elliptical_arbitrary
info:
  polarization: te
  wavelength: 1.554
module: gdsfactory.components.grating_coupler_elliptical_arbitrary
name: grating_coupler_elliptical_arbitrary
settings:
  bias_gap: 0
  cross_section: xs_sc
  fiber_angle: 15.0
  gaps:
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  layer_slab: SLAB150
  nclad: 1.443
  polarization: te
  spiked: true
  taper_angle: 60.0
  taper_length: 16.6
  taper_to_slab_offset: -3.0
  wavelength: 1.554
  widths:
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
