function: rectangle_with_slits
info: {}
module: gdsfactory.components.rectangle_with_slits
name: rectangle_with_slits
settings:
  centered: false
  layer: WG
  layer_slit: SLAB150
  size:
  - 100.0
  - 200.0
  slit_enclosure: 10
  slit_size:
  - 1.0
  - 1.0
  slit_spacing:
  - 20
  - 20
