function: bend_circular
info:
  dy: 10.0
  length: 15.708
  radius: 10.0
  route_info_length: 15.708
  route_info_n_bend_90: 1.0
  route_info_type: xs_sc
  route_info_weight: 15.708
  route_info_xs_sc_length: 15.708
module: gdsfactory.components.bend_circular
name: bend_circular
settings:
  angle: 90.0
  cross_section: xs_sc
