function: via_stack
info:
  layer: M2
  size:
  - 11.0
  - 11.0
  xsize: 11.0
  ysize: 11.0
module: gdsfactory.components.via_stack
name: via_stack_299d6cc0
settings:
  correct_size: true
  layers:
  - HEATER
  - M2
  size:
  - 11.0
  - 11.0
  slot_horizontal: false
  slot_vertical: false
  vias:
  - null
  - function: via
    module: gdsfactory.components.via
    settings:
      enclosure: 2
      layer: VIA1
