function: add_grating_couplers_with_loopback_fiber_array
info:
  length: 20000.009
  polarization: te
  wavelength: 1.53
module: gdsfactory.components.add_grating_couplers
name: spiral_inner_io_add_grating_couplers_with_loopback_fiber_array_with_loopbackFalse
settings:
  bend:
    function: bend_euler
  component:
    component: spiral_inner_io
    settings:
      length: 20000.0
  cross_section: xs_sc
  gc_port_name: o1
  gc_rotation: -90
  grating_coupler:
    function: grating_coupler_elliptical_trenches
    module: gdsfactory.components.grating_coupler_elliptical_trenches
    settings:
      polarization: te
      taper_angle: 35
  grating_separation: 127.0
  loopback_yspacing: 4.0
  select_ports:
    function: select_ports
    module: gdsfactory.port
    settings:
      port_type: optical
  straight_separation: 5.0
  with_loopback: false
