function: cutback_component
info:
  components: 80
module: gdsfactory.components.cutback_component
name: cutback_component
settings:
  bend180:
    function: bend_euler
    module: gdsfactory.components.bend_euler
    settings:
      angle: 180
  cols: 4
  component:
    function: taper_from_csv
  cross_section: xs_sc
  mirror: false
  mirror1: false
  mirror2: false
  port1: o1
  port2: o2
  rows: 5
