function: ring_double_heater
info: {}
module: gdsfactory.components.ring_double_heater
name: ring_double_heater
settings:
  bend:
    function: bend_euler
  coupler_ring:
    function: coupler_ring
  cross_section: xs_sc
  cross_section_heater: xs_heater_metal
  cross_section_waveguide_heater: xs_sc_heater_metal
  gap: 0.2
  length_x: 1.0
  length_y: 0.01
  radius: 10.0
  straight:
    function: straight
  straight_heater:
    function: straight
  via_stack:
    function: via_stack
    module: gdsfactory.components.via_stack
    settings:
      layers:
      - HEATER
      - M2
      - MTOP
      size:
      - 4
      - 4
      vias:
      - null
      - function: via
        module: gdsfactory.components.via
        settings:
          enclosure: 2
          layer: VIA1
      - function: via
        module: gdsfactory.components.via
        settings:
          layer: VIA2
  via_stack_offset:
  - 1
  - 0
