function: dicing_lane
info: {}
module: gdsfactory.components.dicing_lane
name: dicing_lane
settings:
  layer_dicing: DICING
  marker:
    function: triangle
    module: gdsfactory.components.triangles
    settings:
      layer: MTOP
      xtop: 2
  size:
  - 50
  - 300
