function: coh_tx_dual_pol
info: {}
module: gdsfactory.components.coh_tx_dual_pol
name: coh_tx_dual_pol
settings:
  cross_section: xs_sc
  splitter: mmi1x2
  spol_coh_tx: coh_tx_single_pol
  xspacing: 40.0
  yspacing: 10.0
