function: via_stack_corner45
info:
  layer: MTOP
module: gdsfactory.components.via_stack
name: via_stack_corner45
settings:
  correct_size: true
  layers:
  - M1
  - M2
  - MTOP
  vias:
  - function: via
    module: gdsfactory.components.via
    settings:
      enclosure: 2
      layer: VIA1
  - function: via
    module: gdsfactory.components.via
    settings:
      layer: VIA2
  - null
  width: 10
