function: mzi
info: {}
module: gdsfactory.components.mzi
name: mzi_1fc24805
settings:
  add_electrical_ports_bot: true
  add_optical_ports_arms: false
  bend:
    function: bend_euler
  combiner:
    function: coupler
  cross_section: xs_sc
  delta_length: 10.0
  length_x: 0.1
  length_y: 2.0
  min_length: 0.01
  mirror_bot: false
  nbends: 2
  port_e0_combiner: o4
  port_e0_splitter: o4
  port_e1_combiner: o3
  port_e1_splitter: o3
  splitter:
    function: coupler
  straight:
    function: straight
  with_splitter: true
