function: straight_pin_slot
info: {}
module: gdsfactory.components.straight_pin_slot
name: straight_pin_slot
settings:
  cross_section:
    function: pin
  length: 500.0
  taper:
    function: taper_strip_to_ridge
  via_stack:
    function: via_stack
    module: gdsfactory.components.via_stack
    settings:
      layers:
      - M1
      - M2
      - MTOP
      vias:
      - function: via
        module: gdsfactory.components.via
        settings:
          enclosure: 2
          layer: VIA1
      - function: via
        module: gdsfactory.components.via
        settings:
          layer: VIA2
      - null
  via_stack_slab:
    function: via_stack_slot
    module: gdsfactory.components.via_stack_slot
    settings:
      layer_offsets:
      - 0
      layers:
      - M1
      via:
        function: via
        module: gdsfactory.components.via
        settings:
          layer: VIAC
  via_stack_slab_spacing: 2.0
  via_stack_spacing: 3.0
  via_stack_width: 10.0
