function: die_bbox_frame
info: {}
module: gdsfactory.components.die_bbox_frame
name: die_bbox_frame
settings:
  bbox:
  - - -1.0
    - -1.0
  - - 3.0
    - 4.0
  layer: MTOP
  padding: 10.0
  street_length: 1000.0
  street_width: 100.0
  text_anchor: sw
  text_size: 100.0
