function: bend_circular_heater
info:
  dx: 10.0
  dy: 10.0
  length: 15.708
module: gdsfactory.components.bend_circular_heater
name: bend_circular_heater
settings:
  angle: 90
  cross_section: xs_sc
  heater_to_wg_distance: 1.2
  heater_width: 0.5
  layer_heater: HEATER
