function: taper
info:
  length: 100.0
  width1: 0.5
  width2: 0.2
module: gdsfactory.components.taper
name: taper_1db74a4f
settings:
  cross_section: xs_sc
  length: 100
  port_names:
  - o1
  - o2
  port_types:
  - optical
  - edge_te
  width1: 0.5
  width2: 0.2
  with_two_ports: true
