function: coh_tx_single_pol
info: {}
module: gdsfactory.components.coh_tx_single_pol
name: coh_tx_single_pol
settings:
  balanced_phase_shifters: false
  cross_section: xs_sc
  mzm:
    component: mzi
    settings:
      cross_section_x_top: xs_pin
      delta_length: 10.0
      straight_x_top: straight_pin
  mzm_length: 200.0
  mzm_ps_spacing: 40.0
  mzm_y_spacing: 50.0
  pad_array: pad_array
  phase_shifter: straight_pin
  phase_shifter_length: 100.0
  splitter: mmi1x2
  with_pads: false
  xspacing: 40.0
