function: terminator
info: {}
module: gdsfactory.components.terminator
name: terminator
settings:
  cross_section_input:
    function: cross_section
    module: gdsfactory.cross_section
    settings:
      radius: 10
      radius_min: 5
  doping_layers:
  - NPP
  doping_offset: 1.0
  length: 50
  tapered_width: 0.2
