function: coupler90
info: {}
module: gdsfactory.components.coupler90
name: coupler90_528aa9f7
settings:
  bend:
    function: bend_circular
  cross_section: xs_sc
  gap: 0.2
  radius: 10.0
  straight:
    function: straight
