function: cdsem_coupler
info: {}
module: gdsfactory.components.cdsem_coupler
name: cdsem_coupler
settings:
  cross_section: xs_sc
  gaps:
  - 0.15
  - 0.2
  - 0.25
  length: 420.0
  spacing: 7.0
  text:
    function: text_rectangular
    module: gdsfactory.components.text_rectangular
    settings:
      size: 1
