function: spiral_external_io
info:
  length: 9003.302
module: gdsfactory.components.spiral_external_io
name: spiral_external_io
settings:
  N: 6
  bend:
    function: bend_euler
  cross_section: xs_sc
  inner_loop_spacing_offset: 0.0
  mirror_straight: false
  with_inner_ports: false
  x_inner_length_cutback: 300.0
  x_inner_offset: 0.0
  xspacing: 3.0
  y_straight_inner_top: 0.0
  y_straight_outer_offset: 0.0
  yspacing: 3.0
