function: via_stack_slot
info:
  size:
  - 11.0
  - 11.0
  xsize: 11.0
  ysize: 11.0
module: gdsfactory.components.via_stack_slot
name: via_stack_slot
settings:
  enclosure: 1.0
  layer_offsets:
  - 0
  - 1.0
  layers:
  - M1
  - M2
  size:
  - 11.0
  - 11.0
  via:
    function: via
    module: gdsfactory.components.via
    settings:
      enclosure: 2
      layer: VIA1
  ysize: 0.5
  yspacing: 2.0
