function: bend_euler
info:
  dy: 0.0
  length: 42.817
  radius: 10.0
  radius_min: 9.086
  route_info_length: 42.817
  route_info_n_bend_90: 2.0
  route_info_type: xs_sc
  route_info_weight: 42.817
  route_info_xs_sc_length: 42.817
  width: 0.5
module: gdsfactory.components.bend_euler
name: bend_euler_angle180
settings:
  angle: 180
  cross_section: xs_sc
  direction: ccw
  p: 0.5
  with_arc_floorplan: true
