function: splitter_tree
info: {}
module: gdsfactory.components.splitter_tree
name: splitter_tree_92783473
settings:
  bend_s:
    function: bend_s
  coupler:
    function: mzi
    module: gdsfactory.components.mzi
    settings:
      combiner:
        function: mmi2x2
      delta_length: 0
      length_x: null
      port_e0_combiner: o4
      port_e1_combiner: o3
      straight_x_top:
        function: straight_heater_metal_undercut
        module: gdsfactory.components.straight_heater_metal
        settings:
          length_straight_input: 0.1
          length_undercut: 5
          length_undercut_spacing: 0
          with_undercut: false
  cross_section: xs_sc
  noutputs: 4
  spacing:
  - 500
  - 100
