function: coh_rx_single_pol
info: {}
module: gdsfactory.components.coh_rx_single_pol
name: coh_rx_single_pol
settings:
  bend: bend_euler
  cross_section: xs_sc
  det_spacing:
  - 60.0
  - 50.0
  detector:
    function: ge_detector_straight_si_contacts
  hybrid_90deg:
    function: mmi_90degree_hybrid
  in_wg_length: 20.0
  pad_det_spacing: 80.0
  with_pads: true
