function: cutback_2x2
info:
  components: 80
module: gdsfactory.components.cutback_2x2
name: cutback_2x2
settings:
  bend180:
    function: bend_circular
    module: gdsfactory.components.bend_circular
    settings:
      angle: 180
  cols: 4
  component:
    function: mmi2x2
  cross_section: xs_sc
  mirror: false
  port1: o1
  port2: o2
  port3: o3
  port4: o4
  rows: 5
