function: grating_coupler_rectangular_arbitrary_slab
info:
  fiber_angle: 15
  polarization: te
  wavelength: 1.55
module: gdsfactory.components.grating_coupler_rectangular_arbitrary_slab
name: grating_coupler_rectangular_arbitrary_slab
settings:
  cross_section: xs_sc
  fiber_angle: 15
  gaps:
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  layer_slab: SLAB150
  length_taper: 150.0
  polarization: te
  slab_offset: 2.0
  taper:
    function: taper_strip_to_ridge
    module: gdsfactory.components.taper
    settings:
      layer_slab: SLAB150
  wavelength: 1.55
  width_grating: 11.0
  widths:
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
