function: cdsem_straight
info: {}
module: gdsfactory.components.cdsem_straight
name: cdsem_straight
settings:
  cross_section: xs_sc
  length: 420.0
  spacing: 7.0
  text:
    function: text_rectangular
    module: gdsfactory.components.text_rectangular
    settings:
      size: 1
  widths:
  - 0.4
  - 0.45
  - 0.5
  - 0.6
  - 0.8
  - 1.0
