function: coupler90
info: {}
module: gdsfactory.components.coupler90
name: coupler90
settings:
  bend:
    function: bend_euler
  cross_section: xs_sc
  gap: 0.2
  radius: 10.0
  straight:
    function: straight
