function: pad
info:
  layer:
  - 49
  - 0
  size:
  - 80
  - 80
  xsize: 80
  ysize: 80
module: gdsfactory.components.pad
name: pad_sizepad_size
settings:
  layer: MTOP
  port_inclusion: 0
  size: pad_size
