function: edge_coupler_array_with_loopback
info: {}
module: gdsfactory.components.edge_coupler_array
name: edge_coupler_array_with_loopback
settings:
  alignment_port: o1
  angle: 0
  bend:
    function: bend_euler
  cross_section: xs_sc
  edge_coupler:
    function: taper
    module: gdsfactory.components.taper
    settings:
      length: 100
      port_types:
      - optical
      - edge_te
      width2: 0.2
      with_two_ports: true
  extension_length: 1.0
  n: 8
  pitch: 127.0
  place_x_by_port: true
  radius: 30
  right_loopback: true
  space_y_by_port: false
  straight:
    function: straight
  text:
    function: text_rectangular
  text_mirror: false
  text_offset:
  - 0
  - 0
  text_rotation: 0
  x_reflection: false
