function: coh_rx_dual_pol
info: {}
module: gdsfactory.components.coh_rx_dual_pol
name: coh_rx_dual_pol
settings:
  bend:
    function: bend_euler
  cross_section: xs_sc
  lo_splitter: mmi1x2
  single_pol_rx_spacing: 50.0
  splitter_coh_rx_spacing: 40.0
  spol_coh_rx:
    function: coh_rx_single_pol
