function: straight_heater_doped_rib
info: {}
module: gdsfactory.components.straight_heater_doped_rib
name: straight_heater_doped_rib
settings:
  cross_section:
    function: cross_section
    module: gdsfactory.cross_section
    settings:
      radius: 10
      radius_min: 5
      sections:
      - hidden: false
        layer: SLAB90
        name: slab
        offset: 0
        port_names:
        - null
        - null
        port_types:
        - optical
        - optical
        width: 0.2
  cross_section_heater:
    function: rib_heater_doped
  heater_gap: 0.8
  heater_width: 2.0
  length: 320.0
  nsections: 3
  taper:
    function: taper_cross_section
  via_stack:
    function: via_stack
    module: gdsfactory.components.via_stack
    settings:
      layers:
      - SLAB90
      - NPP
      - M1
      vias:
      - null
      - null
      - function: via
        module: gdsfactory.components.via
        settings:
          layer: VIAC
  via_stack_gap: 0.0
  via_stack_metal:
    function: via_stack
    module: gdsfactory.components.via_stack
    settings:
      layers:
      - M1
      - M2
      - MTOP
      vias:
      - function: via
        module: gdsfactory.components.via
        settings:
          enclosure: 2
          layer: VIA1
      - function: via
        module: gdsfactory.components.via
        settings:
          layer: VIA2
      - null
  via_stack_metal_size:
  - 10.0
  - 10.0
  via_stack_size:
  - 10.0
  - 10.0
  width: 0.5
  xoffset_tip1: 0.2
  xoffset_tip2: 0.4
