function: array_with_fanout
info: {}
module: gdsfactory.components.array_with_fanout
name: array_with_fanout
settings:
  bend: bend_euler
  columns: 3
  component: pad
  component_port_name: e4
  cross_section: xs_sc
  end_straight_length: 40.0
  pitch: 150.0
  start_straight_length: 5.0
  waveguide_pitch: 10.0
