function: splitter_tree
info: {}
module: gdsfactory.components.splitter_tree
name: splitter_tree
settings:
  bend_s:
    function: bend_s
  coupler:
    function: mmi1x2
  cross_section: xs_sc
  noutputs: 4
  spacing:
  - 90.0
  - 50.0
