function: via_stack_with_offset
info: {}
module: gdsfactory.components.via_stack_with_offset
name: via_stack_with_offset
settings:
  layers:
  - PPP
  - M1
  size:
  - 10
  - 10
  vias:
  - null
  - function: via
    module: gdsfactory.components.via
    settings:
      layer: VIAC
